2019-08-31 00:39:49,908 : ERROR : Exception on /demo [GET] [in /home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jevisan/ourPersonalities/app/main/routes.py", line 172, in demo
    return render_template('demo.html', title='ourPersonalities Demo', demos=demos)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jevisan/ourPersonalities/app/templates/demo.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jevisan/ourPersonalities/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 26, in block "body"
    {% block scripts %}
  File "/home/jevisan/ourPersonalities/app/templates/demo.html", line 30, in block "scripts"
    window.location = {{ url_for('/analysis_results/') }}+demo
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/analysis_results/'. Did you mean 'main.analysis_results' instead?
2019-08-31 00:40:07,989 : INFO : ourPersonalities startup [in /home/jevisan/ourPersonalities/app/__init__.py:74]
2019-08-31 00:40:10,556 : ERROR : Exception on /demo [GET] [in /home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jevisan/ourPersonalities/app/main/routes.py", line 172, in demo
    return render_template('demo.html', title='ourPersonalities Demo', demos=demos)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jevisan/ourPersonalities/app/templates/demo.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jevisan/ourPersonalities/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 26, in block "body"
    {% block scripts %}
  File "/home/jevisan/ourPersonalities/app/templates/demo.html", line 30, in block "scripts"
    window.location = {{ url_for('main.analysis_results/') }}+demo
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/jevisan/UAM/PT/source/ourPersonalities/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.analysis_results/'. Did you mean 'main.analysis_results' instead?
2019-08-31 00:40:30,660 : INFO : ourPersonalities startup [in /home/jevisan/ourPersonalities/app/__init__.py:74]
