2019-09-04 22:05:19,441 : ERROR : Exception on /register [GET] [in /home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jevisan/ourPersonalities/app/main/routes.py", line 62, in register
    form = RegistrationForm()
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask_wtf/form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask_wtf/csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask_wtf/csrf.py", line 47, in generate_csrf
    setattr(g, field_name, s.dumps(session[field_name]))
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/itsdangerous/serializer.py", line 166, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/itsdangerous/url_safe.py", line 42, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/itsdangerous/serializer.py", line 133, in dump_payload
    return want_bytes(self.serializer.dumps(obj, **self.serializer_kwargs))
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/itsdangerous/_json.py", line 18, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'7d3b558357f50d8f6e0218cc6b045843735daa63' is not JSON serializable
2019-09-04 22:06:50,434 : INFO : ourPersonalities startup [in /home/jevisan/ourPersonalities/app/__init__.py:74]
2019-09-04 22:06:53,901 : ERROR : Exception on /login [GET] [in /home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jevisan/ourPersonalities/app/main/routes.py", line 37, in login
    form = LoginForm()
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask_wtf/form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask_wtf/csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/flask_wtf/csrf.py", line 47, in generate_csrf
    setattr(g, field_name, s.dumps(session[field_name]))
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/itsdangerous/serializer.py", line 166, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/itsdangerous/url_safe.py", line 42, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/itsdangerous/serializer.py", line 133, in dump_payload
    return want_bytes(self.serializer.dumps(obj, **self.serializer_kwargs))
  File "/home/jevisan/ourPersonalities/venv/lib/python3.5/site-packages/itsdangerous/_json.py", line 18, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'7d3b558357f50d8f6e0218cc6b045843735daa63' is not JSON serializable
2019-09-20 12:58:10,053 : INFO : ourPersonalities startup [in /home/jevisan/ourPersonalities/app/__init__.py:74]
2019-09-20 13:00:16,436 : INFO : ourPersonalities startup [in /home/jevisan/ourPersonalities/app/__init__.py:74]
2019-09-20 13:00:48,525 : INFO : ourPersonalities startup [in /home/jevisan/ourPersonalities/app/__init__.py:74]
2019-09-20 13:01:16,440 : INFO : ourPersonalities startup [in /home/jevisan/ourPersonalities/app/__init__.py:74]
2019-09-20 13:03:47,668 : INFO : ourPersonalities startup [in /home/jevisan/ourPersonalities/app/__init__.py:74]
2019-09-20 13:06:07,590 : INFO : ourPersonalities startup [in /home/jevisan/ourPersonalities/app/__init__.py:74]
2019-09-20 16:05:07,704 : INFO : ourPersonalities startup [in /home/jevisan/ourPersonalities/app/__init__.py:74]
2019-09-21 17:32:12,049 : INFO : ourPersonalities startup [in /home/jevisan/ourPersonalities/app/__init__.py:74]
